AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  censio-api-user

Globals:
  Function:
    Timeout: 10

Resources:
  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Environment:
        Variables:
          DB_HOST: !Ref DbHost
          DB_USER: !Ref DbUser
          DB_PASS: !Ref DbPassword
          DB_NAME: !Ref DbName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Parameters:
  DbHost:
    Type: String
    Description: The database host
  DbPort:
    Type: String
    Description: The database port
  DbUser:
    Type: String
    Description: The database user
  DbPassword:
    Type: String
    Description: The database password
  DbName:
    Type: String
    Description: The database name
