name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyodbc
        pip install -r requirements.txt

    - name: Install AWS SAM CLI
      run: |
        pip install aws-sam-cli

    - name: Build SAM application
      run: |
        sam build

    - name: Deploy SAM application
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        sam deploy --no-confirm-changeset --capabilities CAPABILITY_IAM --stack-name censio-api-user --region eu-west-1 --parameter-overrides DbHost=$DB_HOST DbUser=$DB_USER DbPassword=$DB_PASS DbName=$DB_NAME
